apiVersion: v1
kind: Pod
metadata:
  labels:
    qa: java
spec:
  containers:
  - name: jnlp
    image: registry.4paradigm.com/tester_jenkins_slave
    imagePullPolicy: Always
    env:
      - name: TZ
        value: "Asia/Shanghai"
    volumeMounts:
      - mountPath: "/mnt"
        name: "chromedownload"
      - mountPath: "/etc/localtime"
        name: "host-time"
  - name: make
    image: registry.4paradigm.com/tester_java
    imagePullPolicy: Always
    env:
      - name: TZ
        value: "Asia/Shanghai"
    volumeMounts:
      - mountPath: "/mnt"
        name: "chromedownload"
      - mountPath: "/etc/localtime"
        name: "host-time"
    command:
    - cat
    tty: true
  volumes:
    - name: "host-time"
      hostPath:
        path: "/etc/localtime"
    - name: "chromedownload"
      nfs:
        server: 172.27.128.122
        path: "/home/nfs-share"
  imagePullSecrets:
    - name: docker4paradigm